databases:
  - name: "Banco A"
    host: "192.168.1.1"
    port: "3306"
    user: "usuario"
    password: "senha"
    database: "bd_empresa"
    dialect: "mysql"
    version: "8.0"
  - name: "Banco B"
    host: "192.163.1.2"
    port: "5432"
    user: "usuario"
    password: "senha"
    database: "bd_cliente"
    dialect: "postgresql"
    version: "13"

