databases:
  - name: "MariaDB"
    host: "localhost"
    port: 3306
    user: "root"
    password: "senha"
    database: "empresa"
    driver: "mysql+pymysql"
  - name: "PostgreSQL"
    host: "localhost"
    port: 5432
    user: "postgres"
    password: "senha"
    database: "bd_empresa"
    driver: "postgresql+psycopg2"

